#!/usr/bin/bash

HOME=/home/tarkan
XAUTHORITY=$HOME/.Xauthority
export XAUTHORITY HOME
DISPLAY=:0; export DISPLAY;

# Path to lock file
lock="/tmp/keyboard_script.lock"

# Lock the file
exec 9> "$lock"
if ! flock -n 9; then
    notify-send -t 5000 "Keyboard script is already running."
    exit 1
fi

/usr/bin/su tarkan -c "sleep 1; /usr/local/bin/keyboard;" &

# The lock file will be unlocked when the script ends
echo ' ' > "$lock" &
unset DISPLAY
