-- code formatting and highlighting
return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
        ensure_installed = {
            "arduino",
            "bash",
            "c",
            "cpp",
            "dockerfile",
            "dot",
            "doxygen",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "html",
            "java",
            "javascript",
            "json",
            "json5",
            "jsonc",
            "kconfig",
            "latex",
            "lua",
            "make",
            "markdown",
            "markdown_inline",
            "ninja",
            "objc",
            "objdump",
            "python",
            "ssh_config",
            "starlark",
            "t32",
            "udev",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
        },
        highlight = { enable = true },
        indent = { enable = true },  
    }
}
